[package]
name = "servo"
version = "0.0.1"
authors = ["nobody@mozilla.org"]
license = "MPL-2.0"
description = "Rust code for libxul"

[dependencies.geckoservo]
git = "https://github.com/servo/servo"

[lib]
path = "lib.rs"

