language: rust
rust:
    - nightly
    - beta
    - stable
script:
    - cargo test
    - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features unstable)

branches:
  except:
    - master
notifications:
  webhooks: http://build.servo.org:54856/travis
